language: c
dist: xenial

# Build on pushes only to given branches
branches:
  only:
    - master

env:
  global:
    - CI_NODE_TOTAL=6
      # Quickest to build, fast performing, debugable builds.
    - CFLAGS="-g1 -O1"
    - MAKEFLAGS=-j3

# Parallel jobs listed here; fastest jobs should come first to give
# feedback ASAP. For more info read this:
# https://docs.travis-ci.com/user/multi-os/
matrix:
  include:
    - os: linux
      env: JOB_TYPE=compile_and_unit_test_asan
    - os: linux
      env: JOB_TYPE=compile_and_unit_test COVERAGE=no
      compiler: clang
    - os: osx
      env: JOB_TYPE=compile_and_unit_test COVERAGE=no

before_install:
  - chmod ug+x ./travis-scripts/*
  - ./travis-scripts/before_install.sh

script: ./travis-scripts/script.sh

after_success: ./travis-scripts/after_success.sh
